version: '3.6'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certificates:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    logging: *default-logging
    restart: always
  nginx-proxy-acme:
    image: nginxproxy/acme-companion:v1.13
    volumes:
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certificates:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging: *default-logging
    restart: always
volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  dhparam:
  certificates:
  acme:
