version: '3.6'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - ./config/vhost.d:/etc/nginx/vhost.d
      - ./config/html:/usr/share/nginx/html
      - ./config/htpasswd:/etc/nginx/htpasswd
      - ./config/dhparam:/etc/nginx/dhparam
      - ./config/certificates:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    logging: *default-logging
    restart: always
  nginx-proxy-acme:
    image: nginxproxy/acme-companion:v1.13
    volumes:
      - ./config/vhost.d:/etc/nginx/vhost.d
      - ./config/html:/usr/share/nginx/html
      - ./config/dhparam:/etc/nginx/dhparam
      - ./config/certificates:/etc/nginx/certs
      - ./data/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging: *default-logging
    restart: always
